### ISSUE TITLE
Bluetooth lost after waking fro hibernation

### ISSUE THREAD

**Issue by elfzweik** [tlefko/Matebook-X-Pro-2018-Ventura#16]
**Describe the bug**
@tlefko Unfortunately I met the problem of bluetooth lost again after using the release 2.1.7. It does not occur everytime waking from hibernation. As far as I tested, the bluetooth functions correctly when it wakes from sleep, i.e, the display turns off but the fn key light still on, system can be woken by pressing any key. 

But if the fn key light turns off, the system goes into deep sleep, or hibernation. Here I met 2 kinds of situation:

1. The bluetooth still works, but it takes longer to connect the bluetooth peripherals. And when I use Hackintool to check the peripheral, bluetooth is empty. If the machine goes into hibernation again, bluetooth will be lost for sure after waking up. If the machine goes into hibernation again with bluetooth lost, I even met once the bluetooth manufacturer being recognized as Apple. Of course, the bluetooth does not function in this situation. And I have to shut down the machine to recover it, as restart cannot fix it, the bluetooth manufacturer remains Apple and bluetooth does not function.

2. The bluetooth does not work. And Hackintool peripheral shows empty.

I have disabled Other Wakeup Sources in Bios already.

**Comment by doggie13** [comment]
Yea, happens to me too. @tlefko is already aware of this bug and will probably fix it in the next release.

**Comment by elfzweik** [comment]
@doggie13 Thanks for the reply. By the way, do you meet the same problem as I met for booting Windows and Linux error via  OC?

**Comment by doggie13** [comment]
@elfzweik nah, I'm not dual booting.

**Comment by tlefko** [comment]
> @doggie13 Thanks for the reply. By the way, do you meet the same problem as I met for booting Windows and Linux error via OC?

i’m looking into that when i got the chance. I think we can get around it by assigning opencore a singable key for secure boot using linux to generate it

**Comment by tlefko** [comment]
> Yea, happens to me too. @tlefko is already aware of this bug and will probably fix it in the next release.

This is the plan, am waiting for some kext updates

**Comment by tommy762** [comment]
I have had the similar issue: My bluetooth stops working after waking up from hibernation. But restarting the machine can fix it. (Though this works only 90% of the time; sometimes it takes two restarts.) A seperate issues is the touchpad sometimes (10% of the time) stops working after restart.
