### ISSUE TITLE
Laptop freezes when watching YouTube videos.

### ISSUE THREAD

**Issue by doggie13** [tlefko/Matebook-X-Pro-2018-Ventura#17]
Hey guys, I'm wondering if anyone is experiencing such an issue. When I play a video on YouTube in safari, after a minute or two my laptop hangs and doesn't respond to anything, needs to be powered off using the button. It also freezes after a while if I pause the video. Started happening a couple days ago and is present on both 2.1.6 and 2.1.7. Running latest Monterey.

**Comment by tlefko** [comment]
Check the GPU power settings in voltageshift, sounds like it may be related to that.

**Comment by tlefko** [comment]
> Deleted entire voltageshift folder, issue persists.

Appears to be a common issue in the latest batch of monterey updates, extensively usnig safari with too many tabs I was able to replicate this issue. Looking for a solution.

Meantime, I recommended everyone stay below 12.4
<img width="769" alt="Screen Shot 2022-05-31 at 7 45 42 PM" src="https://user-images.githubusercontent.com/42879340/171301657-4b3a5be9-152b-40c7-b75e-f3740e300e7d.png">
