### ISSUE TITLE
BSOD for Windows 11 when booting from OpenCore menu but works fine with Bios boot

### ISSUE THREAD

**Issue by coolpal7** [tlefko/Matebook-X-Pro-2018-Ventura#19]
Firstly, thanks a lot for sharing this work. I used your EFI to install 12.4 Monterey on my i7 Matebook X Pro 2018 and was able to successfully get the Mac OS working along with Windows 11 on Samsung 970 Eve Plus 1TB SSD (replaced the OEM Samsung SSD that was listed as not compatible with OC). Noticed some quirks in Mac OS like battery draining fast in sleep and Wifi stops working randomly but otherwise everything works great.

The biggest issue I have is with dual booting windows. I had to change the ScanPolicy (Misc --> Security) to 0 for Windows boot menu to show up in OC, but when I boot using the OC boot menu into Windows it ends up with BSOD.

Sorry if its a mistake I am doing, but so far couldn't figure it out, and with my little knowledge in this area, it appears to be something with the ACPI, which I have no clue how to troubleshoot. Any help is greatly appreciated.

**Comment by coolpal7** [comment]
It appears we can edit the config.plist to conditionally inject APCIs but I am not very comfortable with it, so going to give rEFInd a try.

regarding other MacOS issues, I noticed the system went unresponsive after WiFi stopped working today. When I looked at the crash report, it said something about Panic from mDNS. Any info on what could be wrong?

**Comment by tlefko** [comment]
Hey, so from what I understand we need to there is ACPI patches for it however to be honest I never explored this as I only use macOS. Personally, I just used the bios f12 menu. However, an alternative boot loader such as reFIND may work and perhaps there is a way to point OC to bootmgr.efi or something of the sort. (the correct windows boot executable)

**Comment by coolpal7** [comment]
Thanks for the feedback. Yes, I have been able to use rEFInd to successfully load either windows or Mac OS and disabled all other boot loaders in bios. Works great. 

Now just need to figure out stability issues with WiFi and it'll be perfect.
