### ISSUE TITLE
AirDrop & Touchscreen

### ISSUE THREAD

**Issue by catfrog** [tlefko/Matebook-X-Pro-2018-Ventura#24]
Meanwhile on OC 0.8.3. and 12.4.  to get  AirDrop and touch Screen working.

Anyone successfull in one of the two above ?

**Comment by tlefko** [comment]
@catfrog hey, so airdrop will not work due to the intel wifi chip. However, touch screen should be working. can you provide more information

**Comment by catfrog** [comment]
First of all thx for picking up and confirming that Airdrop will not work (at the Moment) berauscht of the Intel Chip and the Kext.
Was expecting that touch Screen is an easy one if you know how to.
Problem might be that I am using the 2020 i7 Model with the 10. gen CPU?
Thought I only need to deactivate the kext and ist would be running, without knowing what‘s behind.
No clue about the ACPI stuff but willing to learn, if possible.
Any hint / Link is welcome.

**Comment by tlefko** [comment]
waittttt so this EFI is ac actually working for the 2020 model??? that’s
crazy. not even meant to support it. let me check out the touch screen for
you probably ACPI relayed. how’s everything else

**Comment by tlefko** [comment]
> There are two different Laptops, one ist the 2018 owned by a friend and mine, the 2020. Today I got the 2018 for testing purpose to try everything with your current EFI, mainly sound, sleep and touch Screen.
> 
> Step two will be the same with my own device afterwards, using the same EFI, knowing exactly what went wrong if so.
> 
> Will come back with my findings short term.
> 
> 2018 X Pro:
> 
> Can confirm Touch Screen, Audio, Function Keys, Camera is working as expected,)
> 
> WLAN currently not working, will have a closer look (solved by updating the Kexts).
> 
> Some messages at start rushing over the screen, maybe because of unmatched config.plist and OpenCore? Solved by OC Update.
> 
> Very interessted on how Touch Screen is enabled or disabled and how this takes place.
> 
> On top I am looking for the DSDT & SSDT comments to follow up, unfortunately I can not find them?
> 
> Couldn‘t wait, just updated to OC 0.8.3. Changing the sequence for one Kext to avoid an error message from OCAT.
> 
> 2020 X Pro: Would like to lift up your EFI for the 2020 Model together with you?

Looks like you are correct, those errors are definitely caused by a mismatched OC and config. I am super interested in working on the 2020 project with you. With regards to the dsdt and ssdts, I did not do a great job commenting them. let me know which files you need to work on or have questions about! I would love to contribute towards this

@catfrog

**Comment by catfrog** [comment]
That Sounds great. Since 3 years I am interessted in Hackintosh, owning several different devices.
Looking for a real nice one which I found with the X Pro. Now I am the point that I want to know more about the differences between the 2018 and 2020 model, to go on.
Currently I am looking for the best, easiest and efficents way to proceed with the ACPI stuff.
Should I start from scratch, Building them with the 2020 and compare them with yours?
Have you got an idea/ proposal on how to proceed at the best?
Think I will start with an overwiew whats available on both sides, trying to find out whats the function of each.

**Comment by catfrog** [comment]
<img width="275" alt="Bildschirmfoto 2022-08-19 um 16 45 00" src="https://user-images.githubusercontent.
<img width="735" alt="Bildschirmfoto 2022-08-19 um 16 47 11" src="https://user-images.githubusercontent.com/111204196/186995603-743361cc-0561-4344-af59-3607ee010254.png">
com/111204196/186995597-1bf1ef47-b853-4457
<img width="239" alt="Bildschirmfoto 2022-08-26 um 16 56 50" src="https://user-images.githubusercontent.com/111204196/186995609-64bff676-2ff1-4b82-a4cf-43e78c7fa0a0.png">
-a05e-769025c90693.png">
<img width="198" alt="Bildschirmfoto 2022-08-26 um 16 55 58" src="https://user-images.githubusercontent.com/111204196/186995616-afbe8462-48ad-471c-9368-f3d564255a5c.png">

**Comment by catfrog** [comment]
<img width="550" alt="Bildschirmfoto 2022-08-26 um 23 59 35" src="https://user-images.githubusercontent.com/111204196/186996266-afc1d15f-4697-4e92-be78-964469ae9922.png">

**Comment by tlefko** [comment]
> That Sounds great. Since 3 years I am interessted in Hackintosh, owning several different devices. Looking for a real nice one which I found with the X Pro. Now I am the point that I want to know more about the differences between the 2018 and 2020 model, to go on. Currently I am looking for the best, easiest and efficents way to proceed with the ACPI stuff. Should I start from scratch, Building them with the 2020 and compare them with yours? Have you got an idea/ proposal on how to proceed at the best? Think I will start with an overwiew whats available on both sides, trying to find out whats the function of each.
> 
> As a first start see below, the first are the ones I am currently using for the 2020 model the second the ones used by you. Starting at the point that we might have different Bios versions and therefore locations/pointer might not match even the content could be the same. On your side there is a DSDT, missing on my side, that's the point we have to check and clear at first.

Hey, I'm really sorry for the extreme delay. Got super distracted and busy during the university year. Let me know if you're still interested in collaborating @catfrog, super interested in working with this.

**Comment by catfrog** [comment]
Now I have to excuse for my delay, still interested.

**Comment by tlefko** [comment]
@catfrog let's do it. So DSDT.aml is a central DSDT that is pretty redundant in a lot of ways. Esentiallly it is the entire BIOS DSDT patched into one document, but a lot of the stuff covered in it is done through other patches. It is pretty disorganized to be entirely honest. However, I will publishing a slightly updated release shortly that addresses some other bugs. Let's work from that version.

**Comment by catfrog** [comment]
@tlefko That sounds great.
Somehow I had to do it anyway, because my system crashed after a win update. So everything is still there but will not boot. Used EasyUEFI to (re) generate a new bootentry but without success.
Will generate an OpenCore 0.8.6. Stick to boot with. At first without EFI, Kext …..
The rest will follow step by step,)
