### ISSUE TITLE
Issues with Samsung SSDs

### ISSUE THREAD

**Issue by Paxolo** [tlefko/Matebook-X-Pro-2018-Ventura#28]
**Describe the bug**
My computer randomly restarts during the installation procedure saying: "Your computer was restarted because of a problem".

**To Reproduce**
The last time I tried, I
1. Launched Disk Utility to erase my SSD.
2. Clicked on 'View all devices'
3. Chose my SSD, then clicked on 'Erase'
4. Selected APFS and GUID Partition Map, then started the erasing process
5. After a few seconds, my PC froze for a while and restarted with the message mentioned above

**Screenshots**
![image](https://user-images.githubusercontent.com/53195387/189536777-27f45449-4a34-4f9e-bdf7-f3b14b53ede6.png)

**Specs**
 - OS: macOS Catalina, however I tried Big Sur as well and it seems to behave the same way
 - Laptop model: Huawei Matebook X Pro 2018 (i7 8550U, MX150, 8GB RAM, 512GB Samsung NVMe SSD)
 - BIOS version: whichever one my laptop shipped with.

**Comment by elfzweik** [comment]
I have the same problem recently. In fact, I met the same problem more than 1 year before. At that time I was using Windows 10. Blue screen shows many times everyday. I went to the service center of Huawei. They told me they met this problem frequently. It was because the temparature inside is too high and cause SSD damage. I replaced an SSD and the problem disapeared for more than 1 year until last week. The same crash happened frequently no matter with MacOS or Windows. I found 1 post saying this may be caused by the c-state failure of CPU. Since there is no option in Matebook's bios to disable c-state, I tried to disable it in the reg. After doing that, no crash happens for serveral hours till now. I will continue to watch whether this is a real resolution.

**Comment by elfzweik** [comment]
Confirmed the SSD is not damaged. After I set both ACSettingIndex and DCSettingIndex  the 3 subitems of  HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\54533251-82be-4824-96c1-47b60b740d00\5d76a2ca-e8c0-402f-a133-2158492d58ad\DefaultPowerSchemeValues  to 1, no blue screen happens for the whole week. But this is not a good resolution, for the CPU will not go idle with this setting. 
After further research,  just set the Intel(R) Management Engine Interface in System Devices of Device Manager of Windows to not allow computer shut down this device for power saving, will also work. And the CPU can go idle. This is an ideal resolution. 
However I don't know how to make adjustment in MacOS to disable powersave for Intel Management Engine Interface. MacOS continues to crash. @tlefko do you know how to set?

**Comment by Paxolo** [comment]
My problem never had anything to do with Windows, though.

I went ahead and bought a new NVMe SSD for my laptop, the SN570 if I remember correctly.
That solved all the installation issues for me, and I've had macOS running smoothly ever since.

I know that's not a proper solution, but I was planning on upgrading my storage anyway, so I killed two birds with one stone.

**Comment by tlefko** [comment]
This is super interesting @elfzweik @Paxolo, sorry for the extreme delay. So I am not entirely sure how to disable that  power save feature on the interface however I did add some updated NVME patches and assorted to the new update. These ensure compatibility with Ventura and may offer a potential fix. However, based on what you guys are saying it seems a little unlikely. There are lots of issues with these Samsung drives, especially the ones with intel optane simply being incompatible. I will try to look into this further

**Comment by irodeanu** [comment]
Same issue for my with Samsung ssd MZVLB512HAJQ-00000.

![IMG_0935](https://user-images.githubusercontent.com/5019858/202553734-2a8afd2e-e1a6-4711-a26c-65780bb56e45.jpg)

So I order a Kingston NV2 500GB and now I wait to arrive and test it.

I come back with results.

**Comment by MR-ZiWeiter** [comment]
The same. My Samsung 970PRO has the same problem.

**Comment by tlefko** [comment]
> The same. My Samsung 970PRO has the same problem.

At the moment I have no solution for the problem

**Comment by elfzweik** [comment]
After upgrading the Samsung SSD's firmware, I didn't meet the restart problem for 3 months.

**Comment by elfzweik** [comment]
Just update the status. When I upgraded Samsung 980 Pro's firmware to the newest version 5B2QGXA7, which was released after 0E error was reported by many large companies, the system crash problem was settled, in all platforms, Win11, Macos 12, and Ubuntu 22.04.
