### ISSUE TITLE
Would you mind create a guild of how to do the clean installation

### ISSUE THREAD

**Issue by Tabgach** [tlefko/Matebook-X-Pro-2018-Ventura#31]
I tried to download the recovery version from [gibMacOS](https://github.com/corpnewt/gibMacOS) and create a usb installer then copy ur EFI.  but it cannot boot into installation anymore ,  only show the UEFI shell,  would you mind help to create a guilde of how to do the clean installation

**Comment by Fr33GitHub** [comment]
Change the UEFI Driver from OpenHfsPlus.efi to HfsPlus.efi with OpenCoreConfigurator solves the issue on my system. The boot picker now shows all boot options.

**Comment by tlefko** [comment]
> Change the UEFI Driver from OpenHfsPlus.efi to HfsPlus.efi with OpenCoreConfigurator solves the issue on my system. The boot picker now shows all boot options.

thank you for discovering the cause of this bug @Fr33GitHub. I will include this in the next release and credit you in the notes.

**Comment by tlefko** [comment]
@Tabgach This is the solution.

**Comment by tlefko** [comment]
> I tried to download the recovery version from [gibMacOS](https://github.com/corpnewt/gibMacOS) and create a usb installer then copy ur EFI. but it cannot boot into installation anymore , only show the UEFI shell, would you mind help to create a guilde of how to do the clean installation

It will be a full installation guide coming out shortly
