### ISSUE TITLE
Only the source code in the latest release

### ISSUE THREAD

**Issue by HTA86** [tlefko/Matebook-X-Pro-2018-Ventura#32]
In the latest release only the source code is available
Unfortunately, I don't know how to build from it.

I appreciate your work 👍

![image](https://user-images.githubusercontent.com/45520107/202854080-eac75848-b8f5-448f-a031-7c9a110548f6.png)

**Comment by tlefko** [comment]
@HTA86 thank you for that, didn't realize!

Added the build

**Comment by HTA86** [comment]
Thanks so much
