### ISSUE TITLE
First reboot failing post ventura installation

### ISSUE THREAD

**Issue by akmarwah03** [tlefko/Matebook-X-Pro-2018-Ventura#34]
I tried to install Ventura 13.1 and 13.0.1 using the latest EFI MBXP Ventura 1.1.1. Installation goes well and I can boot into the laptop but first restart shows this error and I am unable to boot into the laptop. I was using Monterey before this with no issues.

1. Install Ventura using latest EFI 
2. Restart the laptop
3. Select Mac OS

**Expected behavior**
Laptop should boot normally.

**Screenshots**
![WhatsApp Image 2022-12-14 at 00 48 16](https://user-images.githubusercontent.com/78773141/207549173-1c543267-9659-4e3e-80c4-4e191533e6d6.jpg)
![WhatsApp Image 2022-12-14 at 00 48 16](https://user-images.githubusercontent.com/78773141/207549196-abf74eff-aeca-4827-b2a6-77bc3fea89d4.jpg)

**Desktop (please complete the following information):**
 - OS: Ventura 13.1/13.0.1
 - EFI: MBXP Ventura 1.1.1

**Comment by tlefko** [comment]
It would appear you still have the Ventura USB inside the machine. Did you
copy ventura EFI to the EFI partition of the HDD? I can't quite tell if
this is booting the Ventrua or Monterey EFI. Also, I would enable verbose
mode in the config file and send me the output if it is indeed booting off
the correc EFI. Hard to tell whats going on without it.

**Comment by Paxolo** [comment]
Now that winter break started here in Italy I have some time to try to update my machine to Ventura.
I'm willing to perform a clean installation of the OS as I don't mind losing files I have stored locally.
However, I think there might be something wrong with release 1.1.1, as I get the very same error even when trying to boot to the macOS 13 Installer.

What I believe @akmarwah03 did is copy the newest EFI folder to the EFI partition of his hackintosh drive and update to Ventura via the System Preferences app.
This is the only way I can think of to get macOS 13 installed using the latest release.

**Comment by akmarwah03** [comment]
@Paxolo actually at first I tried installing from System Preferences that failed. After that I made a new bootable usb for ventura with latest efi, I was able to do a clean install with succesful boot but restart results in this error, I have tried both with usb and replacing hdd efi with new one post install, both end up the error. I will try verbose and let you know @tlefko. I have already formatted the HDD so its a clean install.

**Comment by akmarwah03** [comment]
New update, clean install mac os 13.0.1 with latest efi working after restart as well.

**Comment by tlefko** [comment]
> New update, clean install mac os 13.0.1 with latest efi working after restart as well.
> Thought the bluetooth isn't working, showing no devices.
> <img alt="Screenshot 2022-12-17 at 8 14 09 PM" width="476" src="https://user-images.githubusercontent.com/78773141/208280957-669f65a0-5050-4d55-aaec-710575cf1fab.png">

Glad to see that everything worked out for you, macOS Ventura has proven to be very different from previous releases.  What did you end up changing to get it to boot? For me, the restart after the installation took a very long time and that was the only difficult part for me
