### ISSUE TITLE
Need help for installation.

### ISSUE THREAD

**Issue by Lucas2k8** [tlefko/Matebook-X-Pro-2018-Ventura#35]
Hi, I´m a Spanish filmaker and I'm trying to install Monterrey to use FCPX on my 2018 Matebook Pro X and I'm a little bit lost.

According to everything I have been able to read and understand, the first thing I should do is make a clean install of catalina, but as I have been able to read in another thread, my computer restarts after it has been installing for 10 minutes and I cannot solve that step. I have the MateBook X Pro with the i7, mx150 ,8gb of ram and the nvmd 512gb of Samsung. I readed another thread with a similar problem, but the solution whas use a more recent release and didn't worked :(

I could not find how to solve this step, I also have not been able to understand if it is possible to install Monterrey directly, making a bootable with opencore.

If there is any guide or someone could give me some help, I would be very grateful. I know that the problem is me and that I must be doing something wrong, but the only thing I know to do in life is follow video tutorials 😖

Thanks

**Comment by naxvm** [comment]
Hello, Lucas.

Some of us have also had this issue. The solution for this is to replace your NVMe SSD, since the Samsung model presents some incompatibilities with this OS.

In my case, after replacing the SSD, the sudden reboots finished.

I hope it is helpful!

**Comment by Lucas2k8** [comment]
@naxvm 
Hello Nacho.

Thanks for your answer. I have tried to install it on an external nvme via usb and it works!

Now I just need to swap the nvme from my external hard drive to the laptop one.

One last question. To install monterrey, I just have to install catalina first, and once downloaded, download the monterrey installer and run it?

Thanks!

**Comment by tlefko** [comment]
@naxvm @Lucas2k8 the samsung SSD is defintiely the cause here, I still am unsure how to resolve this issue. But yes, basically that is correct in order to install monterey. This is as the installer won't boot for some reason off a USB in my experience. Hopefully, we can figure out some sort of solution possibly related to APFStrim.

**Comment by tlefko** [comment]
@Lucas2k8 I would use the Monterey EFI in order to install Monterey, the last or second last before ventura. I would use one of the earliest releases in order to install catalina.

**Comment by Lucas2k8** [comment]
Thanks @tlefko for all the help and support. I managed to install a new 2tb crucial nvme and now it works perfectly fine. 
I'll try in a few days to install monterrey with the second last before ventura, now i'm in monterrey and i don't like it too much hehe. 
Thanks for everything.

**Comment by tlefko** [comment]
@Lucas2k8 im sorry to hear that! yes it can be a little buggy. How is the performance and all the other features? 

-- thank you for the donation, much appreciated by the way/

-tlefko

**Comment by Lucas2k8** [comment]
@tlefko The overall performance is great, it works similar to my 2017 Macbook pro(gpu dead), but with better battery performance and touchscreen working in Final cut pro x.
It doesn't overheat editing photo or video, but i think that the matebook can be a little bit faster in monterrey.
Bluetooth doesn't always work, and the wifi isn't perfect, but it works. 
In any case, thanks for all your work and effort!

**Comment by tlefko** [comment]
> @tlefko The overall performance is great, it works similar to my 2017 Macbook pro(gpu dead), but with better battery performance and touchscreen working in Final cut pro x.
> It doesn't get hot editing photo or video, but i think that the matebook can be a little bit faster in monterrey.
> Bluetooth doesn't always work, and the wifi isn't perfect, but it works.
> In any case, thanks for all your work and effort!

love to her! doing my best to fix this
