### ISSUE TITLE
Extended Bluetooth Features

### ISSUE THREAD

**Issue by tlefko** [tlefko/Matebook-X-Pro-2018-Ventura#8]
Hey all, so i’ve been testing out extending continuity consistency with bluetooth modifications. Please try to test the Airplay features of the Mac! I’ve recently been experimenting with success getting monterey’s airplay (using matebook as a speaker) and as an apple tv device to cast media to. This requires ZERO input from the hackintosh itself. all controlled thru whatever is casting to it. including the macs volume, video playback, etc

![7A03417E-FE18-47C0-A8A8-A1A55949DD28](https://user-images.githubusercontent.com/42879340/163279403-6f36eee6-3ff8-4a74-a3f4-c50d0934a570.png)

![C13F12CE-98F9-40D4-A599-139904704C7E](https://user-images.githubusercontent.com/42879340/163279211-9eddb5ac-0cc3-4891-a206-83a795862a9c.png)

Please try sharing your experience with continuity features such as Apple Watch Unlock, etc.

With a tool called BLEUnlock, progress is wild!

**Comment by francescodesu** [comment]
Thank you for your hard work!

For me continuity, handoff, airplay are working!

Universal control, sidecar, airdrop, Apple Watch unlock not working.

It would be super cool if we could have universal control working at some point :)

**Comment by tlefko** [comment]
> Thank you for your hard work!
> 
> For me continuity, handoff, airplay are working!
> 
> Universal control, sidecar, airdrop, Apple Watch unlock not working.
> 
> It would be super cool if we could have universal control working at some point :) 

Really, I know the airdrop does not work proplely but sidecar / universal control seemed to work under my testing. can you share your experience. @francescodesu I worked on it a while ago! I agree, needed feature!

**Comment by francescodesu** [comment]
BLEUnlock works flowlessly!

sidecar gives the error "the device timed out"... Any idea on how to solve it?

**Comment by tlefko** [comment]
So first thing to check is whether your SMBIOS is changed (ROM, MLB, etc).
I would then reccomend signing in and out of icloud on all devices and
restarting. Also disable home view on the Ipad from what I read. We can
also explore different SMBIOS models to change and attempt (Macbook Pro
13,4 13,1 etc)

**Comment by francescodesu** [comment]
Thanks, it seems that sidecar works with the thunderbolt cable but not through Bluetooth.

I tried restarting the device, re-logging to iCloud, and I have tried Macbook Pro 14,2 and 15,2 SMBIOS but it does not seem to work... Which SMBIOS are you using?

**Comment by tlefko** [comment]
i would try 13,1 or 13,3. Make sure the extendbtfeatureflag is enabled in
the config
